[package]
name = "freya-query"
description = "Fully-typed, async, reusable cached data management for Freya ðŸ§¬"
version = "0.4.0-rc.6"
edition = "2024"
license = "MIT"
authors = ["Marc EspÃ­n <mespinsanz@gmail.com>"]
readme = "../../README.md"
homepage = "https://freyaui.dev/"
repository = "https://github.com/marc2332/freya"
keywords = ["freya", "async", "state", "synchronization"]
categories = ["gui", "asynchronous"]

[package.metadata.docs.rs]
features = ["freya-core/mocked-engine"]

[features]
skia-engine = ["freya-core/skia-engine"]

[dependencies]
freya-core = { workspace = true }
futures-util = { workspace = true }
async-io = { workspace = true }

[dev-dependencies]
freya = { path = "../freya" }
freya-testing = { path = "../freya-testing" }
