[package]
name = "ragnarok"
description = "UI Events processor. Originally made for Freya but works for other libraries."
version = "0.4.0"
edition = "2024"
license = "MIT"
authors = ["Marc Esp√≠n <mespinsanz@gmail.com>"]
readme = "./README.md"
homepage = "https://freyaui.dev/"
repository = "https://github.com/marc2332/freya"
keywords = ["gui", "ui"]
categories = ["gui"]

[dependencies]
euclid = { workspace = true }
itertools = { workspace = true }
tracing = { workspace = true }
rustc-hash = { workspace = true }

# Performance
hotpath = { workspace = true }

[features]
hotpath = ["hotpath/hotpath"]
hotpath-alloc = ["hotpath/hotpath-alloc"]
hotpath-off = ["hotpath/hotpath-off"]
