[package]
name = "freya-node-state"
description = "Internal Node states for Dioxus RealDOM elements used in Freya."
version = "0.3.0"
edition = "2021"
license = "MIT"
authors = ["Marc Esp√≠n <mespinsanz@gmail.com>"]
readme = "../../readme.md"
homepage = "https://freyaui.dev/"
repository = "https://github.com/marc2332/freya"
keywords = ["gui", "ui", "desktop", "skia", "dioxus"]
categories = ["gui", "asynchronous"]

[package.metadata.docs.rs]
features = ["freya-engine/mocked-engine"]

[features]
skia-engine = ["freya-engine/skia-engine"]

[dependencies]
freya-common = { workspace = true }
freya-engine = { workspace = true }
torin = { workspace = true }

freya-native-core-macro = { workspace = true }
freya-native-core = { workspace = true }
dioxus-core = { workspace = true }

tokio = { workspace = true }
accesskit = { workspace = true }
shipyard = { workspace = true }
rustc-hash= { workspace = true }
tracing = { workspace = true }

uuid = { workspace = true }
bytes = "1.5.0"
serde_json = "1.0.107"
