[package]
name = "freya-router-macro"
version = "0.4.0-alpha.3"
authors = ["Evan Almloff", "Marc Esp√≠n <mespinsanz@gmail.com>"]
edition = "2024"
description = "Macro for Freya Router"
license = "MIT"
repository = "https://github.com/marc2332/freya/"
keywords = ["gui", "ui", "desktop", "skia", "freya"]

[lib]
proc-macro = true


[dependencies]
syn = { version = "2.0.103", features = ["extra-traits", "full"] }
quote = "1.0.40"
proc-macro2 = "1.0.95"
slab = "0.4.10"

[dev-dependencies]
freya = { path = "../freya" }
freya-router = { path = "../freya-router" }
