[package]
name = "freya-winit"
version = "0.4.0-alpha.1"
edition = "2024"
license = "MIT"
authors = ["Marc Esp√≠n <mespinsanz@gmail.com>"]
readme = "../../README.md"
homepage = "https://freyaui.dev/"
repository = "https://github.com/marc2332/freya"
keywords = ["gui"]
categories = ["gui", "asynchronous"]

[package.metadata.docs.rs]
features = ["freya-engine/mocked-engine"]

[dependencies]
freya-core = { workspace = true }
freya-components = { workspace = true }
torin = { workspace = true }

# Rendering
bytes = { workspace = true }

# Rendering OpenGL
gl = { workspace = true }
glutin = { workspace = true }
glutin-winit = { workspace = true }

# Rendering VUlkan
ash = { workspace = true, optional = true }
ash-window = { workspace = true, optional = true }

# Window
raw-window-handle = { workspace = true }
winit = { workspace = true }
freya-engine = { workspace = true }

# Events
ragnarok = { workspace = true }
keyboard-types = { workspace = true }

# Accessibility
accesskit_winit = { workspace = true }
accesskit = { workspace = true }

# Other
futures-channel = { workspace = true }
futures-util = { workspace = true }
rustc-hash = { workspace = true }

# Performance
hotpath = { workspace = true }

# Images
image = { workspace = true }

[features]
hotpath = ["hotpath/hotpath"]
hotpath-alloc = ["hotpath/hotpath-alloc"]
hotpath-off = ["hotpath/hotpath-off"]
vulkan = ["dep:ash", "dep:ash-window", "freya-engine/vulkan"]
skia-engine = ["freya-engine/skia-engine"]
