[package]
name = "freya-devtools-app"
version = "0.4.0-alpha.0"
edition = "2024"

[dependencies]
freya = { workspace = true }
freya-core = { workspace = true }
freya-router = { workspace = true }

freya-radio = { workspace = true }
freya-devtools = { workspace = true }

accesskit = { workspace = true }
serde_json = "1"

async-tungstenite = { version = "0.31" }
futures-util = { workspace = true }
smol = "2.0.2"
tungstenite = { version = "0.27", features = ["handshake"] }
async-lock = { version = "3.4.1" }
