[package]
name = "freya-clipboard"
version = "0.4.0-alpha.8"
edition = "2024"
description = "Clipboard integration for Freya."
license = "MIT"
authors = ["Marc Esp√≠n <mespinsanz@gmail.com>"]
homepage = "https://github.com/marc2332/freya"
repository = "https://github.com/marc2332/freya"
keywords = ["freya"]
categories = ["gui"]

[package.metadata.docs.rs]
features = ["freya-core/mocked-engine"]

[features]
skia-engine = ["freya-core/skia-engine"]

[dependencies]
copypasta = "0.10"
freya-core = { workspace = true }
