[package]
name = "freya-router"
authors = ["Marc Esp√≠n <mespinsanz@gmail.com>"]
version = "0.4.0-alpha.0"
edition = "2024"
description = "Router management for Freya apps"
license = "MIT"
readme = "./README.md"
repository = "https://github.com/marc2332/freya/"
keywords = ["gui", "ui", "desktop", "skia", "freya"]

[dependencies]
freya-core = { workspace = true }
freya-router-macro = { workspace = true }

urlencoding = "2.1.3"
url = "2.5.4"
rustversion = "1.0.21"

[dev-dependencies]
freya = { workspace = true }
