[package]
name = "freya-router-macro"
version = "0.3.0"
authors = ["Evan Almloff", "Marc Esp√≠n <mespinsanz@gmail.com>"]
edition = "2021"
description = "Macro for Freya Router"
license = "MIT"
repository = "https://github.com/marc2332/freya/"
keywords = ["gui", "ui", "desktop", "skia", "dioxus"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.103", features = ["extra-traits", "full"] }
quote = "1.0.40"
proc-macro2 = "1.0.95"
slab = "0.4.10"
base16 = "0.2.1"
digest = "0.10.7"
sha2 = "0.10.9"

[dev-dependencies]
freya = { workspace = true }
freya-router = { workspace = true }