[package]
name = "freya-radio"
version = "0.4.0-alpha.0"
edition = "2024"
description = "Fully-typed global state management with a topics subscription system for Freya ðŸ§¬"
categories = ["gui"]
license = "MIT"

[features]
tracing = ["dep:tracing", "dep:itertools"]

[dependencies]
freya-core = { workspace = true }

# Logging
itertools = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }

[dev-dependencies]
freya = { workspace = true }
freya-testing = { workspace = true }
