[package]
name = "freya-performance-plugin"
version = "0.4.0-alpha.0"
edition = "2024"

[package.metadata.docs.rs]
features = ["freya-engine/mocked-engine"]

[dependencies]
freya-winit = { workspace = true }
freya-engine = { workspace = true }
