[package]
name = "freya-icons"
version = "0.4.0-alpha.0"
edition = "2024"
description = "Icons library for Freya."
authors = ["Marc Esp√≠n <mespinsanz@gmail.com>"]
readme = "../../README.md"
homepage = "https://freyaui.dev/"
repository = "https://github.com/marc2332/freya"
keywords = ["gui"]
categories = ["gui", "asynchronous"]

[features]
skia = ["freya-engine/skia-engine"]
# Icons
all = ["lucide"]
lucide = []

[dependencies]
freya-core = { workspace = true }
freya-engine = { workspace = true }
bytes = { workspace = true }
