[package]
name = "freya-plotters-backend"
description = "Freya's skia-safe backend for plotters"
version = "0.4.0-rc.7"
edition = "2024"
license = "MIT"
authors = ["Marc Esp√≠n <mespinsanz@gmail.com>"]
readme = "./README.md"
repository = "https://github.com/marc2332/freya"
keywords = ["gui", "plot", "backend", "skia", "plotters"]
categories = ["gui"]

[package.metadata.docs.rs]
features = ["freya-engine/mocked-engine"]

[features]
skia-engine = ["freya-engine/skia-engine"]

[dependencies]
freya-engine = { workspace = true }
plotters-backend = "0.3.7"

[dev-dependencies]
plotters = "0.3.7"
