[package]
name = "freya-core"
description = "Internal core funcionatilies for Freya."
version = "0.3.0"
edition = "2021"
license = "MIT"
authors = ["Marc Esp√≠n <mespinsanz@gmail.com>"]
readme = "../../readme.md"
homepage = "https://freyaui.dev/"
repository = "https://github.com/marc2332/freya"
keywords = ["gui", "ui", "desktop", "skia", "dioxus"]
categories = ["gui", "asynchronous"]

[package.metadata.docs.rs]
features = ["freya-engine/mocked-engine"]

[features]
shared = []
skia-engine = ["freya-engine/skia-engine"]

[dependencies]
freya-node-state = { workspace = true }
freya-elements = { workspace = true }
freya-common = { workspace = true }
freya-engine = { workspace = true }
torin = { workspace = true }

freya-native-core = { workspace = true }
dioxus-core = { workspace = true }

tokio = { workspace = true }
winit = { workspace = true }
accesskit = { workspace = true }

rustc-hash = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
itertools = "0.13.0"
smallvec = { workspace = true }

[dev-dependencies]
dioxus = { workspace = true }
freya = { path = "../freya" }
freya-testing = { path = "../testing" }
