[package]
name = "freya-native-core"
description = "Native DOM for Freya"
version = "0.3.0"
edition = "2021"
license = "MIT"
authors = ["Jonathan Kelley", "Evan Almloff", "Marc Esp√≠n <mespinsanz@gmail.com>"]
readme = "./README.md"
homepage = "https://freyaui.dev/"
repository = "https://github.com/marc2332/freya"
keywords = ["gui", "ui", "desktop", "skia", "dioxus"]
categories = ["gui"]

[dependencies]
dioxus-core = { workspace = true}

smallvec = { workspace = true }
rustc-hash = { workspace = true }
parking_lot = { version = "0.12.1", features = ["send_guard"] }
shipyard = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
freya-native-core-macro = { path = "../native-core-macro"}

