name: Rust Lint

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    concurrency:
      group: rust-lint-${{ github.ref_name }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 2
        submodules: true
    - name: Install stable rust toolchain
      uses: dtolnay/rust-toolchain@1.90
      with:
        components: rustfmt, clippy
    - name: Install nightly rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly-2025-09-25
        components: rustfmt
    - name: Install just
      uses: taiki-e/install-action@just
    - name: Install taplo
      uses: taiki-e/install-action@taplo
    - name: Set up cargo cache
      uses: Swatinem/rust-cache@v2
      if: github.ref != 'refs/heads/main'
      with:
        shared-key: "rust-ubuntu-latest"
        save-if: ${{ github.ref == 'refs/heads/main' }}
    - name: Lint
      run: just c
    - name: Format
      run: just f
